### ISSUE TITLE
Visualisation/explanations of different MPI send types

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-intro-to-mpi#30]
Episode: Communicating Data in MPI

One learner found it hard to visualise the difference between MPI send types (MPI_Ssend, MPI-Bsend). Possible fixes:

- Perhaps a diagram could be added to the material to make the differences clearer, and/or
- An analogy added, e.g. SSend is like a phone call, Bsend a letter/email and Rsend is like a position update with air traffic control or something?
- We should also explain how Bsend is async but still a blocking function. The function won’t return until the data has been copied and safe to modify again. It’s blocking because MPI_Ibsend would return before it finished copying the data.
Suggestion: perhaps also include (brief) use cases for when each is useful

**Comment by Edward-RSE** [comment]
Closed with PR #50.
