### ISSUE TITLE
General: code style is inconsistent

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-intro-to-mpi#31]
Episode: All.

The code style is inconsistent, especially with how functions are defined (some parameters are described inline, whilst other examples have a table of parameters).

We should make the code consistent across all code (in the training material markdown and the code examples in repo `code` directory).

**Comment by Edward-RSE** [comment]
I'm working on this in the `code-style` branch. It might take a while...

**Comment by Edward-RSE** [comment]
Closed with PR #53.
