### ISSUE TITLE
Clarify difference between blocking/non-blocking w.r.t. MPI communication functions

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-intro-to-mpi#35]
Episode: Communicating Data in MPI

The difference between blocking and non-blocking is potentially not clear enough. We should make it clearer that there are blocking communication functions and non-blocking functions. So you have to explicitly program non-blocking communication, etc; MPI_Send won’t decide to be blocking or non-blocking.

**Comment by Edward-RSE** [comment]
Closed with PR #50.
