### ISSUE TITLE
Review: 2. Introduction to the Message Passing Interface

### ISSUE THREAD

**Issue by Edward-RSE** [Southampton-RSG-Training/dirac-intro-to-mpi#9]
This issue is to track comments and changes for this episode.

**Comment by Edward-RSE** [comment]
Before I do a more detailed review, following from https://github.com/Southampton-RSG-Training/dirac-intro-to-mpi/issues/8#issuecomment-1607508510 in the episode 1 review, I think there is potential we would consolidate episode 2 and 3 together if we did consolidate episode 1 and 3.

**Comment by Edward-RSE** [comment]
There is also stuff we can borrow and add from our previous DiRAC material: https://southampton-rsg-training.github.io/dirac-code-scaling/dirac-code-scaling-running-example-code-cluster

**Comment by Edward-RSE** [comment]
RE: pull request #21 

I only one comment. I think it's worth saying that the prime problem is easy to split across ranks, because it's an example of an embarrassingly parallel problem (and maybe why it is EP?). And following that, mentioning that not every problem can be broken up like this with reference to, e.g., general problems vs EP problems (reference first episode) and other patterns (e.g. communication patterns episode).

What do you think?

**Comment by steve-crouch** [comment]
Completed.
